// <auto-generated />
namespace VehicleTrackingAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Inital_VTS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Inital_VTS));
        
        string IMigrationMetadata.Id
        {
            get { return "202004201016561_Inital_VTS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
